// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEuxOovywCy_G5s1doibDKGq2xgnIDo0',
    appId: '1:171357650087:web:f8847f2543f02f92f0af82',
    messagingSenderId: '171357650087',
    projectId: 'fir-1-ab8cf',
    authDomain: 'fir-1-ab8cf.firebaseapp.com',
    storageBucket: 'fir-1-ab8cf.firebasestorage.app',
    measurementId: 'G-2264JLWDVH',
    databaseURL: 'https://fir-1-ab8cf-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF30dOP71XeOaaFlU3opd5KkGHN7jNCA4',
    appId: '1:171357650087:android:b4d28cb4f7b93cc0f0af82',
    messagingSenderId: '171357650087',
    projectId: 'fir-1-ab8cf',
    storageBucket: 'fir-1-ab8cf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPEuxOovywCy_G5s1doibDKGq2xgnIDo0',
    appId: '1:171357650087:web:e630efa5df3fff38f0af82',
    messagingSenderId: '171357650087',
    projectId: 'fir-1-ab8cf',
    authDomain: 'fir-1-ab8cf.firebaseapp.com',
    storageBucket: 'fir-1-ab8cf.firebasestorage.app',
    measurementId: 'G-Z0HEFJ4XR3',
  );
}
